# 服务端口
server:
  port: 8001

# 服务名
spring:
  application:
    name: service-edu
  # 环境设置
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///guli?serverTimezone=GMT%2B8
    username: root
    password: root
  # 返回json的时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # nacos注册中心服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper路径
  mapper-locations: classpath:com/xunle/eduservice/mapper/xml/*.xml
  # 逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 开启熔断机制
#feign:
#  hystrix:
#    enabled: true
# 设置hystrix超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        isolate:
#          thread:
#            timeoutInMilliseconds: 6000
