server:
  port: 8006

spring:
  profiles:
    active: dev
  application:
    name: service-ucenter
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # nacos注册中心服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
      shutdown-timeout: 100
    host: 192.168.248.132
    port: 6379

# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置mapper路径
  mapper-locations: classpath:com/xunle/eduservice/mapper/xml/*.xml
  # 逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

mail:
  host: smtp.qq.com
  username: 1601315809@qq.com
  password: xpnsajskvfokhdic
  default-encoding: UTF-8
  sender: 1601315809@qq.com